blank_issues_enabled: true
contact_links:
  - name: Xero Core Security Policy
    url: https://github.com/xero/xero/blob/master/SECURITY.md
    about: View security policy
  - name: Xero Core Developers
    url: https://bitcoincore.org
    about: Xero Core homepage
